#!/bin/bash
# XtrasBackup 全量备份脚本

# =========================================
# 根据实际情况修改下面参数
# =========================================

# 帐号
user=xtrabackup
# 密码
password=xtra@password
# MySQL 配置文件
defaults_file=/etc/my.cnf
# MySQL Socket File
socket=/usr/local/mysql/mysql.sock
# 备份的文件位置
basedir=/usr/local/xtrabackup/base/

/usr/bin/innobackupex --defaults-file=${defaults_file} --user=${user} --password=${password} --socket=${socket} --no-lock ${basedir}
